flags:
packages:
- '.'
- ../gl-pal
- ../udp-pal
- ../bullet-mini
- ../vr-pal
- ../glfw-pal
- ../oculus-mini
- ../hydra-hs
- ../pd-haskell
- ../halive
- ../animation-pal
- ../linear-extra
- ../lens-extra
- ../openvr-hs
extra-deps:
- ekg-0.4.0.7
resolver: nightly-2015-11-03
