flags:
packages:
- '.'
- ../gl-pal
- ../udp-pal
- ../bullet-mini
- ../vr-pal
- ../glfw-pal
- ../pd-haskell
- ../halive
- ../animation-pal
- ../linear-extra
- ../lens-extra
- ../openvr-hs
- ../bindings-GLFW
extra-deps: []
resolver: nightly-2015-12-03
