flags:
packages:
- '.'
- ../gl-pal2
- ../udp-pal
- ../bullet-mini
- ../game-pal
- ../glfw-pal
- ../oculus-mini
- ../hydra-hs
- ../pd-haskell
extra-deps:
- fsnotify-0.1.0.3
- halive-0.1.0.5
- hfsevents-0.1.5
- GLFW-b-1.4.7.2
- bindings-GLFW-3.1.1.3
- Win32-notify-0.3.0.1
- inline-c-0.5.4.3
- inline-c-cpp-0.1.0.0
- ekg-0.4.0.7
- ekg-core-0.1.0.4
resolver: nightly-2015-08-07
arch: x86_64
