flags:
packages:
- '.'
- ../gl-pal
- ../udp-pal
- ../bullet-mini
- ../game-pal
- ../glfw-pal
- ../oculus-mini
- ../hydra-hs
- ../pd-haskell
- ../halive
extra-deps:
- GLFW-b-1.4.7.2
- bindings-GLFW-3.1.1.3
- inline-c-0.5.4.3
- inline-c-cpp-0.1.0.0
- ekg-0.4.0.7
- ekg-core-0.1.0.4
resolver: lts-3.0
arch: x86_64
